
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nixon
  password: 1234
  port: 5432

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test
